Introduce basic shell scripts
Yonas-net/icinga-shell pull request #1
Opened 2021-01-29 16:57 UTC by Yonas-net

2021-01-29 17:07 UTC, Al2Klimov requested changes
I don’t insist on re-writing in Go, but IMAO it would make the following easier.

* Parametrize host, port, user and password of both Icinga 2 and IW2 and `/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d`
* Randomize names of created objects
* Make all output human-readable

2021-02-01 10:26 UTC, Al2Klimov requested changes

2021-02-01 10:26 UTC, Al2Klimov commented on script.sh
> +    printf "\nHost %s object can be found in Icinga Web 2.\n" $object
Those look fine, but...

2021-02-01 10:26 UTC, Al2Klimov commented on script.sh
> +  curl -k -s -u $icinga2Auth -H 'Accept: application/json' -X POST "https://$icinga2Host/v1/actions/restart-process"
... the script shall also echo what **these ones** are doing.

2021-02-01 11:55 UTC, Al2Klimov commented on script.sh
> +  curl -k -s -u $icinga2Auth -H 'Accept: application/json' -X POST "https://$icinga2Host/v1/actions/restart-process"
I also meant sleep and rm.

2021-02-01 12:38 UTC, Al2Klimov requested changes
Have a look what you're doing more than once and put that in functions.

2021-02-01 12:38 UTC, Al2Klimov commented on script.sh
> +  declare "$(echo $1 | sed 's/^-//')=$2"
You’re already setting variables here...

2021-02-01 12:38 UTC, Al2Klimov commented on script.sh
> +confdPath="$cfdPath"
... so why are you setting additional ones with the same stuff?

2021-02-01 12:38 UTC, Al2Klimov commented on script.sh
> +  sleep 10
Please log all sleeps...

2021-02-01 12:38 UTC, Al2Klimov commented on script.sh
> +EOF
... and this one.

2021-02-01 12:38 UTC, Al2Klimov commented on script.sh
> +  echo
... and all curls.

2021-02-01 14:16 UTC, Al2Klimov requested changes

2021-02-01 14:16 UTC, Al2Klimov commented on script.sh
> +  fi
Put the logs in the functions.

2021-02-01 14:16 UTC, Al2Klimov commented on script.sh
> +  if ModifyObject "https://$i2Host/v1/actions/restart-process"; then
Change your functions so they take only variable stuff, i.e. just the host name in this case.

2021-02-01 14:16 UTC, Al2Klimov commented on script.sh
> +  curl=("curl" -skSu "$i2Auth" -H 'Accept: application/json' -X PUT "$1")
This function takes `$1` – an URL...

2021-02-01 14:16 UTC, Al2Klimov commented on script.sh
> +    "vars": { "os": "Linux"} } }'; then
... which is `https://$i2Host/v1/objects/hosts/$object` in this case. What are `-d` `{...}` for in this case?

2021-02-01 14:25 UTC, Yonas-net commented on script.sh
> +  if ModifyObject "https://$i2Host/v1/actions/restart-process"; then
How is this supposed to work? Restarting the process, scheduling a downtime and sending a notification is not the same even if all the queries use the same host.

2021-02-01 14:34 UTC, Al2Klimov commented on script.sh
> +  if ModifyObject "https://$i2Host/v1/actions/restart-process"; then
I mean:

1. Change this function, so you call it: `ModifyObject "$i2Host"`
2. Have a look at the others and change them the same way

2021-02-01 14:45 UTC, Yonas-net commented on script.sh
> +  if ModifyObject "https://$i2Host/v1/actions/restart-process"; then
The function is not only used to restart the process but also for something else, i.e. they do not have the same url e.g ``/v1/actions/schedule-downtime``.

2021-02-01 14:48 UTC, Al2Klimov commented on script.sh
> +  if ModifyObject "https://$i2Host/v1/actions/restart-process"; then
Now I see! o.o Name your functions after what they do.

2021-02-01 14:59 UTC, Yonas-net commented on script.sh
> +    "vars": { "os": "Linux"} } }'; then
For the associated host attributes, how else am I going to create a two hosts with different ``attrs``? I have just used incorrect parameter passing.

2021-02-01 15:02 UTC, Al2Klimov commented on script.sh
> +    "vars": { "os": "Linux"} } }'; then
Exactly. Correct your parameter passing.

2021-02-05 10:54 UTC, Al2Klimov reviewed
Run this and provide the complete output.

2021-02-05 11:00 UTC, Yonas-net commented
```bash
./script.sh -i2Host "localhost:5665" -i2Auth "root:icinga" -iw2Host "10.211.55.14:80" -iw2Auth "icingaadmin:icinga" -cfdPath "/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d"
```

Output:

```bash
Creating Icinga 2 '/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d/host-23008.conf' config file.

Icinga 2 daemon successfully restarted.
Sleep until Icinga 2 has been successfully restarted.
Removing Icinga 2 '/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d/host-23008.conf' config file.

Icinga 2 daemon successfully restarted.
Sleep until Icinga 2 has been successfully restarted.

Host host-23008 object can be found in Icinga Web 2.

Host 'host-23008' object successfully created via API.
Sleep until Icinga 2 reloaded all necessary jobs.

Host host-23008 object can be found in Icinga Web 2.

Host host-23008 object can be found in Icinga 2.

Host 'icinga2' object successfully created via API.
Sleep until Host 'icinga2' object is visible in Icinga Web 2.

Icinga Web 2 host host-23008 object can be found.

Icinga 2 API host host-23008 object found.

Downtime of type 'Host' successfully scheduled.

Sending 'custom' Notification of type 'Host'.

Sleep until all created hosts are visible in Icinga Web 2.

Host 'host-23008' object successfully deleted.
Host 'icinga2' object successfully deleted.

Sleep until all deleted Hosts are also deleted from IDO.
```

2021-02-05 11:11 UTC, Al2Klimov commented
Did you [just](https://github.com/Yonas-net/icinga-shell/pull/1#issuecomment-773962143) reproduce the issue this script is for?

2021-02-05 13:08 UTC, Yonas-net commented
**v2.11.7**:

```bash
Creating Icinga 2 '/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d/host-30592.conf' config file.

Icinga 2 daemon successfully restarted.
Sleep until Icinga 2 has been successfully restarted.
Removing Icinga 2 '/Users/yhabteab/Workspace/icinga2/prefix/etc/icinga2/conf.d/host-30592.conf' config file.

Icinga 2 daemon successfully restarted.
Sleep until Icinga 2 has been successfully restarted.

Host host-30592 object doesn't exists in Icinga Web 2.

Host 'host-30592' object successfully created via API.
Sleep until Icinga 2 reloaded all necessary jobs.

Host host-30592 object doesn't exists in Icinga Web 2.

Host host-30592 object can be found in Icinga 2.

Host 'icinga2' object successfully created via API.
Sleep until Host 'icinga2' object is visible in Icinga Web 2.

Icinga Web 2 host 'icinga2' object can be found.

Icinga 2 API host 'icinga2' object found.

Downtime of type 'Host' successfully scheduled.

Sending 'custom' Notification of type 'Host'.

Sleep until all created hosts are visible in Icinga Web 2.

Host 'host-30592' object successfully deleted.
Host 'icinga2' object successfully deleted.

Sleep until all deleted Hosts are also deleted from IDO.
```

**Master**:

```bash
Coming soon 
```

2021-02-05 14:34 UTC, Al2Klimov requested changes
Squash.

2021-02-05 14:46 UTC, Al2Klimov approved these changes
I don’t like misusing bash for _actual programming_, but it seems to work.

2021-02-05 14:46 UTC, merged